### PR TITLE
Remove play links for pkgs outside std lib

### LINKED ISSUE #308: Remove playground links for code outside the standard library
The example 'Play' for the image package Play is broken.

https://godoc.org/golang.org/x/image/draw?play=Draw
 
golangdrawexampleplayerror
godoc page for the image package.

### PR DESCRIPTION
**Pull request by lucidlime**
Fixes #308.

### CODE REVIEW

**Comment by lucidlime** [comment]
PR #321 addresses this issue by removing the play code when the package is retrieved from the version control system.  This PR removes the play link at the time the package is displayed.  There are two advantages of the approach in this PR:

- The play links disappear immediately when this PR is pushed.  
- The play code is not discarded. If there be a reason to use the code in the future, it's still there.

**Comment by shurcooL** [comment]
I agree the general approach of this PR, to simply hide/not display the link in the template when it's a package outside of standard library, is better than trying to filter out the `doc.Example.Play` when creating documentation because of the 2 reasons you mentioned.

I have a suggestion for the implementation, I'll post it in inline comments.

File: gddo-server/template.go [hunk 1]
```diff
@@ -121,7 +122,13 @@ func (pdoc *tdoc) addExamples(obj interface{}, export, method string, examples [
 		id += "-" + method
 	}
 	for _, e := range examples {
-		te := &texample{Label: label, ID: id, Example: e, obj: obj}
+		te := &texample{
+			Label:        label,
+			ID:           id,
+			Example:      e,
+			ShowPlayLink: e.Play != "" && gosrc.IsGoRepoPath(pdoc.ImportPath),
```
Comment (shurcooL) [inline gddo-server/template.go]: You're doing more complex logic here that is more disconnected (i.e., located further away) from the context where it's actually used.

I suggest adding a new field `Standard`, to mimic [`Standard` in `cmd/go`](https://github.com/golang/go/blob/28ce6f3600fd87a1ae39c492ee56307f0be3c32f/src/cmd/go/pkg.go#L40) (or maybe `Goroot` instead) here, and set its value independently.

File: gddo-server/assets/templates/pkg.html [hunk 2]
```diff
@@ -171,7 +171,7 @@ <h4 class="modal-title">Jump to identifier</h4>
         <div class="panel-heading"><a class="accordion-toggle" data-toggle="collapse" href="#ex-{{.ID}}">Example{{with .Example.Name}} ({{.}}){{end}}</a></div>
         <div id="ex-{{.ID}}" class="panel-collapse collapse"><div class="panel-body">
           {{with .Example.Doc}}<p>{{.|comment}}{{end}}
-          <p>Code:{{if .Example.Play}}<span class="pull-right"><a href="?play={{.ID}}">play</a>&nbsp;</span>{{end}}
+          <p>Code:{{if .ShowPlayLink}}<span class="pull-right"><a href="?play={{.ID}}">play</a>&nbsp;</span>{{end}}
```
Comment (shurcooL) [inline gddo-server/assets/templates/pkg.html]: Then this can contain the decision whether to show the example, like:

```
{{if (and .Example.Play .Standard)}}...{{end}}
```

On second thought, this might not work so great since this template doesn't have access to the top level package, so it's not clear that `.Standard` would mean `.Package.Standard`.

**Comment by lucidlime** [comment]
I prefer to write complex logic in Go code instead of in templates.  This seems to be the approach taken by the surrounding code.

If you prefer more template code, then let's do the following:

- Add field to texample:  `Package *tdoc`
- Add field to tdoc:: `Standard bool`
- Change the template to:  `{{if (and .Example.Play .Package.Standard)}}...{{end}}`

**Comment by shurcooL** [comment]
> I prefer to write complex logic in Go code instead of in templates. This seems to be the approach taken by the surrounding code.

I also prefer to write complex logic in Go rather than templates. I don't think this is complex code. It would change a single boolean condition into the "and" operation of two booleans.

It's also logic that is relevant to presentation, and I think those kinds of decisions are best to keep in the templates. If I were reading the template and saw `<p>Code:{{if .ShowPlayLink}}<span class="pull-...`, I'd have to look in the backend code to figure out how the value of `ShowPlayLink` is set. On the other hand, something like `{{if (and .Example.Play .Package.Standard)}}...{{end}}` is extremely readable and easy to change.

> If you prefer more template code, then let's do the following:
>
> - Add field to texample:  `Package *tdoc`
> - Add field to tdoc:: `Standard bool`
> - Change the template to:  `{{if (and .Example.Play .Package.Standard)}}...{{end}}`

That sounds great, I'm in agreement!

**Comment by lucidlime** [comment]
I'll leave this for you to fix.

**Comment by shurcooL** [comment]
All right, I'll try to take it from here, thanks for getting it this far.

Are you okay if I base it on top your existing change?

**Comment by lucidlime** [comment]
> Are you okay if I base it on top your existing change?

Sure, but does it make sense to do this? None of the changes in this PR are retained in the approach you prefer.

**Comment by shurcooL** [comment]
You did the work to fix the issue, I just reviewed it, so I wanted to preserve your credit.

**Comment by lucidlime** [comment]
I was riding quietly off into the sunset, but now I need to unload.

I don’t agree with what you want here for the reasons I stated. I was going to suck it up and just get the job done, but you came back with more that I disagree with. The exclamation point was the cherry on top!

This project is not for me. I want to write code that I am proud of. I want to spend more time working on code than writing in the issue tracker.

If you want to give credit, give it to jmhodges. His PR has been sitting here for months with no feedback.

**Comment by adg** [comment]
@lucidlime that's not good! Please trust that @shurcooL is just doing his best here. He's a volunteer just like you, who so far has done a good job of reviewing and testing the various changes people have made to gddo. I think he is right to share his concerns when reviewing a PR. If you disagree with the suggestions, you are free to say why and push back.

There's not much interest in maintaining godoc.org. Ultimately the buck stops with me, but I have limited time, so I appreciate any help I can get.

> I want to spend more time working on code than writing in the issue tracker.

It is really important that we keep the codebase (first and foremost) correct and (ultimately) maintainable, especially since there are so few people interested in maintaining it. If I merge a PR that causes production issues then the site can go down until I'm available to do something about it, and Go programmers suffer. So thorough code review is important for the project. I'm sorry if this rubs you the wrong way. :frowning:

**Comment by shurcooL** [comment]
> If you disagree with the suggestions, you are free to say why and push back.

I agree with this. I hold projects under the golang organization to a high standard and am willing to spend more of my free time and effort to help as much as I can. I really like godoc.org, and so I'm happy to discuss solutions and look for ways to make the code better when possible. If someone proposes a better alternative than I could come up with, I'd much rather have that be merged instead.

**Comment by lucidlime** [comment]
> It is really important that we keep the codebase (first and foremost) correct and (ultimately) maintainable, 

In my opinion, the reviewer requested changes that make the code incorrect (PR 380) and less maintainable (this PR and 380). I don't like submitting substandard work to make a reviewer happy. I also don't want to put a large amount of energy into arguing for what I think is right. It's not fun.

Now that I know where the buck stops, I'll reopen this PR. It's OK with me if the PR is rejected with no feedback.

I am on board with thorough code reviews. I'll reconsider my decision to move along from this project.

File: gddo-server/template.go [hunk 3]
```diff
@@ -82,10 +82,11 @@ type tdoc struct {
...
 
 type texample struct {
-	ID      string
-	Label   string
-	Example *doc.Example
-	obj     interface{}
+	ID           string
+	Label        string
+	Example      *doc.Example
+	ShowPlayLink bool
```
Comment (adg) [inline gddo-server/template.go]: I'd rename this field to just Play

File: gddo-server/template.go (hunk 1 above)
Comment (adg) [inline gddo-server/template.go]: Add a comment above this line: 
```
// Don't show play links for packages outside the standard library.
```

**Comment by adg** [comment]
I've left some comments which, if addressed, leave me happy to merge this PR.

I admit I'm having trouble reconciling these two statements:

> I also don't want to put a large amount of energy into arguing for what I think is right. It's not fun.

and

> I am on board with thorough code reviews. 

One seems to preclude the other.

**Comment by lucidlime** [comment]
Renamed to just Play.

Arguing is different from discussing.

**Comment by adg** [comment]
I also made a comment about adding a comment.

> Arguing is different from discussing.

**Comment by lucidlime** [comment]
I cannot find comment about comment.

**Comment by adg** [comment]
Sigh. I hate pull requests. We will switch to Gerrit in this repo soon.

I asked that you add a comment above where you set the `Play` field along the lines of:

```
// Only show play links for packages within the standard library.
```

**Comment by lucidlime** [comment]
I added the comment.

**Comment by adg** [comment]
Thanks.
